### PR TITLE
Better Memory Handling and don´t re-download images

### PR DESCRIPTION
**Pull request by NotCR**
Overall: More memory management on gallery activity and book page fragments, couple UI fixes, couple logic changes for getting image

PageApi ->Change logic to only download images if not present. Past logic checked if existed and re-downloaded them at the same time

FileCacheManager -> Introduces First Version of custom in sample size

GalleryPagerAdapter-> Added eraseItem function (Erase fragments for better memory handling)

BookPageFragment-> More memory cleaning stuff (No more memory leaks in this department :D)

BookDetailsActivity -> Change Picasso for manual loading (Fixes some devices not showing image)

GalleryActivity -> Added on ConfigurationChanged function and logic (Fixes FC´s when rotating)
GalleryActivity -> Forced Garbage Collector every 5 swipes (Free memory faster)

RandomActivity -> Change Picasso for manual loading (Fixes some devices not showing image)

AndroidManifest -> enable onConfigurationChanged for GalleryActivity

Build.Gradle -> Bump to 1.3.2

### CODE REVIEW

**Comment by fython** [comment]
Being busy for another project these days, I am very grateful for your hard work! Thx a lot XD

**Comment by NotCR** [comment]
No Problem, glad to help. Have you tested the changes?

**Comment by fython** [comment]
In fact I haven't tested. I think it might not cause building problems so I directly merged.

**Comment by NotCR** [comment]
I tested on an HTC One M9, Nexus 7 (2012 and 2013). All on OS 6.0.1. Also some friends tested on their devices without problems (ZTE, samsung). Going to start looking into the new API an see if its easier than parsing the whole html (should be)

**Comment by fython** [comment]
Yes, it's easier and faster to read data by getting raw JSON data. And I can get the tags of books from list now(which means blocking some tags is possible)!

**Comment by NotCR** [comment]
we can filter via normal query (we still need the lists of characters, tags, parodies, etc) 

Example: 

https://nhentai.net/api/galleries/search?query=naruto%20tags:yuri%20-tags:milf&page=1
returns naruto + yuri tag - milf tag

https://nhentai.net/api/galleries/search?query=naruto%20tags:yuri&page=1 
returns naruto + yuri tag

Is possible to create a private json in app that stores this lists and make custom queries based on users input (with a friendly UI) 

Any opninions on this?

**Comment by fython** [comment]
I agree with you. Friendly UI is important.

**Pull request merged**
